//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 02:31:23 PM CET 
//


package net.ivoa.pdl.tavernaCommunication02;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JobId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JobPhase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DemandDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessingDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FinishingDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Inputs" type="{}Inputs" minOccurs="0"/>
 *         &lt;element name="Outputs" type="{}Outputs" minOccurs="0"/>
 *         &lt;element name="Errors" type="{}Errors" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jobId",
    "jobPhase",
    "demandDate",
    "processingDate",
    "finishingDate",
    "inputs",
    "outputs",
    "errors"
})
@XmlRootElement(name = "JobDetail")
public class JobDetail {

    @XmlElement(name = "JobId", required = true)
    protected String jobId;
    @XmlElement(name = "JobPhase", required = true)
    protected String jobPhase;
    @XmlElement(name = "DemandDate", required = true)
    protected String demandDate;
    @XmlElement(name = "ProcessingDate")
    protected String processingDate;
    @XmlElement(name = "FinishingDate")
    protected String finishingDate;
    @XmlElement(name = "Inputs")
    protected Inputs inputs;
    @XmlElement(name = "Outputs")
    protected Outputs outputs;
    @XmlElement(name = "Errors")
    protected Errors errors;

    /**
     * Gets the value of the jobId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * Sets the value of the jobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobId(String value) {
        this.jobId = value;
    }

    /**
     * Gets the value of the jobPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobPhase() {
        return jobPhase;
    }

    /**
     * Sets the value of the jobPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobPhase(String value) {
        this.jobPhase = value;
    }

    /**
     * Gets the value of the demandDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDemandDate() {
        return demandDate;
    }

    /**
     * Sets the value of the demandDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDemandDate(String value) {
        this.demandDate = value;
    }

    /**
     * Gets the value of the processingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingDate() {
        return processingDate;
    }

    /**
     * Sets the value of the processingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingDate(String value) {
        this.processingDate = value;
    }

    /**
     * Gets the value of the finishingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinishingDate() {
        return finishingDate;
    }

    /**
     * Sets the value of the finishingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinishingDate(String value) {
        this.finishingDate = value;
    }

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link Inputs }
     *     
     */
    public Inputs getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inputs }
     *     
     */
    public void setInputs(Inputs value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link Outputs }
     *     
     */
    public Outputs getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outputs }
     *     
     */
    public void setOutputs(Outputs value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link Errors }
     *     
     */
    public Errors getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Errors }
     *     
     */
    public void setErrors(Errors value) {
        this.errors = value;
    }

}
